version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  browser-tools: circleci/browser-tools@1.2.4
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build-test-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup

      - run:
          name: Building the project
          command: npm run build
      - run:
          name: testing the project
          command: npm run build
# workflows:
#   sample:
#     jobs:
#       - build-test-deploy
