version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  browser-tools: circleci/browser-tools@1.2.4
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - aws-cli/setup
      - eb/setup
      - checkout
      - run:
          name: installing dependencies
          command: npm run install
      - run:
          name: Building the project
          command: npm run build
      - run:
          name: testing the project
          command: npm run build
      - run:
          name: deploying frontend
          command: npm run deploy:frontend
      - run:
          name: deploying backend
          command: npm run deploy:backend
workflows:
  sample:
    jobs:
      - build
          filters:
              branches:
                only: main
